### ISSUE TITLE
How to use TSGM with GPUs

### ISSUE THREAD

**Issue by Diting-li** [AlexanderVNikitin/tsgm#12]
this is an aowsome project! but generater's loss still higher than D，g loss =10,  d loss=0.001, vanishing gradients

**Comment by AlexanderVNikitin** [comment]
Hi, you don't need anything extra to run on GPU. If a GPU is visible, the code will run on GPU.

Regarding the second question about generator and discriminator loss. Sometimes GANs are difficult to train, so I recommend tweaking network architectures a bit or restarting training. If you provide the code, I can take a look.
