### ISSUE TITLE
Pip installation does not work on M1 chip using Rosetta 2

### ISSUE THREAD

**Issue by tuomijal** [AlexanderVNikitin/tsgm#38]
Hei @AlexanderVNikitin and others,

Thank you for the software and greetings from Tampere University!

**Problem description**
I have a 2020 MacBook Air with M1 chip. With M1 the default installation from PyPI does not currently work using Rosetta 2:

```
arch
> i386

pip install tsgm
python -c 'import tsgm'
> [1]    57761 illegal hardware instruction  python
```

This is because "Google's official TF macos-x86_64 wheel releases on PyPI assumes a target platform that has AVX instructions" as described [here](https://stackoverflow.com/questions/73461385/m1-mac-tensorflow-vs-code-rosetta2)

**Solution**
It is possible to install `tsgm` with Rosetta 2 using conda as follows:

```
# Create a conda environment
conda create -n my-env
conda activate my-env

# Install tensorflow
conda install -c conda-forge tensorflow=2.9.1

# Install tsgm without dependencies
pip install tsgm --no-deps

# Install rest of the dependencies (separately here for clarity)
conda install tensorflow-probability scipy antropy statsmodels dtaidistance networkx optuna prettytable seaborn scikit-learn yfinance tqdm

# Check that it works
python -c "import tsgm; print(tsgm.__name__)
> tsgm
```

I guess this could be resolved by publishing a conda-forge package in addition to the PyPI one?

**Comment by AlexanderVNikitin** [comment]
Thank you, @tuomijal! We've added this workaround to README. Unfortunately, it is common to have problems with TensorFlow on M1 and M2 chips.
